from fpdf import FPDF
import os

OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "data", "unstructured")

class BankPDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 10)
        self.cell(0, 8, "PT Bank Nusantara Tbk - Dokumen Internal", align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(0, 51, 153)
        self.set_line_width(0.5)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.cell(0, 10, f"Rahasia - Hanya untuk Keperluan Internal | Halaman {self.page_no()}/{{nb}}", align="C")

    def add_title(self, title):
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(0, 51, 153)
        self.cell(0, 12, title, align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_text_color(0, 0, 0)
        self.ln(6)

    def add_section(self, title):
        self.set_font("Helvetica", "B", 12)
        self.set_text_color(0, 51, 153)
        self.cell(0, 8, title, new_x="LMARGIN", new_y="NEXT")
        self.set_text_color(0, 0, 0)
        self.ln(2)

    def add_subsection(self, title):
        self.set_font("Helvetica", "B", 10)
        self.cell(0, 7, title, new_x="LMARGIN", new_y="NEXT")
        self.ln(1)

    def add_body(self, text):
        self.set_font("Helvetica", "", 10)
        self.multi_cell(0, 6, text)
        self.ln(2)

    def add_bullet(self, text):
        self.set_font("Helvetica", "", 10)
        self.set_x(10)
        self.multi_cell(0, 6, "  - " + text)


def create_sop_pembukaan_rekening():
    pdf = BankPDF()
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.add_title("SOP Pembukaan Rekening Nasabah")
    pdf.add_body("Nomor Dokumen: SOP/OPS/001/2025\nTanggal Efektif: 1 Januari 2025\nRevisi ke-5 | Disetujui oleh: Direktur Operasional")
    pdf.add_section("1. Tujuan")
    pdf.add_body("Standar Operasional Prosedur (SOP) ini bertujuan untuk memberikan panduan yang jelas dan terstandar mengenai proses pembukaan rekening nasabah baru di PT Bank Nusantara Tbk, baik untuk rekening perorangan maupun badan usaha, guna memastikan kepatuhan terhadap regulasi OJK dan prinsip kehati-hatian perbankan.")
    pdf.add_section("2. Ruang Lingkup")
    pdf.add_body("SOP ini mencakup seluruh proses pembukaan rekening, termasuk:\n- Rekening Tabungan (Tabungan Reguler, Tabungan Bisnis, Tabungan Pelajar)\n- Rekening Giro (Perorangan dan Badan Usaha)\n- Rekening Deposito Berjangka\n- Rekening Valas (USD, SGD, JPY, EUR)\n\nSOP ini berlaku untuk seluruh Kantor Cabang (KC), Kantor Cabang Pembantu (KCP), dan Kantor Kas (KK) di seluruh wilayah operasional Bank Nusantara.")
    pdf.add_section("3. Persyaratan Dokumen Nasabah Perorangan")
    pdf.add_subsection("3.1 Dokumen Wajib (WNI)")
    pdf.add_bullet("Kartu Tanda Penduduk (KTP/e-KTP) yang masih berlaku")
    pdf.add_bullet("Nomor Pokok Wajib Pajak (NPWP) - wajib untuk saldo awal di atas Rp 50.000.000")
    pdf.add_bullet("Pas foto terbaru ukuran 3x4 (2 lembar)")
    pdf.add_bullet("Surat referensi dari nasabah existing atau surat keterangan domisili")
    pdf.add_subsection("3.2 Dokumen Wajib (WNA)")
    pdf.add_bullet("Paspor yang masih berlaku minimal 6 bulan")
    pdf.add_bullet("KITAS/KITAP atau Visa Tinggal Terbatas")
    pdf.add_bullet("Surat Keterangan Domisili dari RT/RW setempat")
    pdf.add_bullet("Surat Referensi dari Bank Asal (untuk WNA dengan rekening di bank lain)")
    pdf.add_subsection("3.3 Dokumen Tambahan Badan Usaha")
    pdf.add_bullet("Akta Pendirian Perusahaan dan perubahannya yang telah disahkan Kemenkumham")
    pdf.add_bullet("Nomor Induk Berusaha (NIB) atau SIUP/TDP")
    pdf.add_bullet("NPWP Perusahaan")
    pdf.add_bullet("KTP seluruh pengurus yang tercantum dalam akta")
    pdf.add_bullet("Surat Kuasa bermaterai (jika pembukaan rekening diwakilkan)")
    pdf.add_bullet("Laporan Keuangan 2 tahun terakhir (untuk fasilitas kredit)")
    pdf.add_section("4. Prosedur Pembukaan Rekening")
    pdf.add_subsection("4.1 Tahap Penerimaan")
    pdf.add_body("a) Customer Service (CS) menyambut calon nasabah dan menjelaskan produk yang tersedia.\nb) CS memverifikasi kelengkapan dokumen sesuai checklist.\nc) CS melakukan pengecekan DHBN (Daftar Hitam Bank Nasional) melalui sistem BI Checking.\nd) CS memastikan calon nasabah tidak termasuk dalam daftar DTPK (Daftar Terduga Pendanaan Terorisme dan Proliferasi).")
    pdf.add_subsection("4.2 Tahap Verifikasi (Enhanced Due Diligence)")
    pdf.add_body("a) Verifikasi identitas melalui sistem Dukcapil untuk validasi NIK.\nb) Pencocokan wajah (face matching) antara foto KTP dan wajah nasabah.\nc) Untuk nasabah dengan profil risiko tinggi (PEP, beneficial owner perusahaan offshore), dilakukan Enhanced Due Diligence (EDD):\n   - Interview mendalam mengenai sumber dana\n   - Verifikasi silang informasi pekerjaan dan penghasilan\n   - Persetujuan Kepala Cabang atau Compliance Officer")
    pdf.add_subsection("4.3 Tahap Input Data")
    pdf.add_body("a) CS menginput data nasabah ke Core Banking System (CBS).\nb) Nomor rekening di-generate secara otomatis oleh sistem.\nc) CS meminta nasabah untuk:\n   - Membuat tanda tangan specimen (3x di kartu specimen)\n   - Menetapkan PIN untuk kartu debit\n   - Aktivasi mobile banking (opsional)\nd) Setoran awal minimal:\n   - Tabungan Reguler: Rp 100.000\n   - Tabungan Bisnis: Rp 500.000\n   - Giro: Rp 1.000.000\n   - Deposito: Rp 10.000.000")
    pdf.add_subsection("4.4 Tahap Persetujuan")
    pdf.add_body("a) Supervisor/Kepala Operasional melakukan otorisasi pembukaan rekening.\nb) Untuk rekening dengan saldo awal > Rp 500.000.000, diperlukan persetujuan Kepala Cabang.\nc) Untuk nasabah PEP (Politically Exposed Person), diperlukan persetujuan Compliance Division Head Office.")
    pdf.add_section("5. Ketentuan Setoran Awal dan Biaya")
    pdf.add_body("Tabel Ketentuan:\n\nProduk               | Setoran Awal  | Admin/Bulan | Saldo Minimum\nTabungan Reguler     | Rp 100.000    | Rp 12.500   | Rp 50.000\nTabungan Bisnis      | Rp 500.000    | Rp 15.000   | Rp 250.000\nTabungan Pelajar     | Rp 25.000     | Gratis      | Rp 10.000\nGiro Perorangan      | Rp 1.000.000  | Rp 25.000   | Rp 500.000\nGiro Badan Usaha     | Rp 5.000.000  | Rp 35.000   | Rp 1.000.000\nDeposito             | Rp 10.000.000 | -           | Rp 10.000.000")
    pdf.add_section("6. Pembukaan Rekening Digital (e-Account Opening)")
    pdf.add_body("Bank Nusantara menyediakan fasilitas pembukaan rekening secara digital melalui aplikasi NusantaraMobile dengan ketentuan:\na) Calon nasabah mengunduh aplikasi NusantaraMobile dari App Store / Google Play.\nb) Proses e-KYC dilakukan melalui:\n   - Upload foto KTP (OCR otomatis)\n   - Verifikasi biometrik (selfie + liveness detection)\n   - Video call dengan CS (untuk rekening di atas Rp 50 juta)\nc) Rekening digital memiliki limit transaksi:\n   - Transfer harian: Rp 25.000.000\n   - Upgrade ke full service: kunjungi cabang terdekat\nd) Rekening digital aktif dalam waktu 1x24 jam setelah verifikasi berhasil.")
    pdf.add_section("7. Penanganan Dokumen dan Arsip")
    pdf.add_body("a) Seluruh dokumen pembukaan rekening disimpan dalam bentuk fisik dan digital.\nb) Dokumen fisik disimpan di brankas cabang selama 5 tahun setelah rekening ditutup.\nc) Dokumen digital di-scan dan di-upload ke Document Management System (DMS).\nd) Akses ke dokumen nasabah dibatasi berdasarkan role dan kebutuhan (need-to-know basis).\ne) Pemusnahan dokumen yang sudah melewati masa retensi dilakukan sesuai SOP Pemusnahan Dokumen.")
    pdf.add_section("8. Sanksi dan Kepatuhan")
    pdf.add_body("Pelanggaran terhadap SOP ini dapat mengakibatkan:\na) Teguran lisan (pelanggaran pertama)\nb) Surat Peringatan (pelanggaran kedua)\nc) Skorsing (pelanggaran ketiga)\nd) Pemberhentian (pelanggaran berat / fraud)\n\nSOP ini mengacu pada:\n- POJK No. 12/POJK.01/2017 tentang Penerapan Program APU PPT\n- PBI No. 23/6/PBI/2021 tentang Penyedia Jasa Pembayaran\n- UU No. 27 Tahun 2022 tentang Perlindungan Data Pribadi\n- SE OJK No. 32/SEOJK.03/2017 tentang CDD")
    pdf.output(os.path.join(OUTPUT_DIR, "01_SOP_Pembukaan_Rekening.pdf"))
    print("Created: 01_SOP_Pembukaan_Rekening.pdf")


def create_panduan_kyc():
    pdf = BankPDF()
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.add_title("Panduan Know Your Customer (KYC)")
    pdf.add_body("Nomor Dokumen: SOP/COMPL/002/2025\nTanggal Efektif: 1 Januari 2025\nRevisi ke-4 | Disetujui oleh: Direktur Kepatuhan")
    pdf.add_section("1. Pendahuluan")
    pdf.add_body("Know Your Customer (KYC) atau Prinsip Mengenal Nasabah adalah prinsip dasar dalam operasional perbankan yang mewajibkan bank untuk mengenali dan memahami identitas nasabah, memantau kegiatan transaksi nasabah, serta melaporkan transaksi yang mencurigakan. Penerapan KYC merupakan bagian integral dari program Anti Pencucian Uang dan Pencegahan Pendanaan Terorisme (APU-PPT) di PT Bank Nusantara Tbk.")
    pdf.add_section("2. Dasar Hukum")
    pdf.add_bullet("UU No. 8 Tahun 2010 tentang Pencegahan dan Pemberantasan Tindak Pidana Pencucian Uang")
    pdf.add_bullet("UU No. 9 Tahun 2013 tentang Pencegahan dan Pemberantasan Tindak Pidana Pendanaan Terorisme")
    pdf.add_bullet("POJK No. 12/POJK.01/2017 tentang Penerapan Program APU PPT di Sektor Jasa Keuangan")
    pdf.add_bullet("SE OJK No. 32/SEOJK.03/2017 tentang Customer Due Diligence")
    pdf.add_bullet("Peraturan PPATK No. 8 Tahun 2021 tentang Pengawasan Kepatuhan")
    pdf.add_section("3. Kategori Risiko Nasabah")
    pdf.add_subsection("3.1 Risiko Rendah")
    pdf.add_body("- Nasabah perorangan dengan penghasilan tetap (pegawai negeri, karyawan swasta)\n- Pelajar/mahasiswa dengan saldo rekening di bawah Rp 100 juta\n- Badan usaha berbadan hukum yang telah beroperasi lebih dari 5 tahun\n- Lembaga pemerintahan dan BUMN/BUMD")
    pdf.add_subsection("3.2 Risiko Menengah")
    pdf.add_body("- Wiraswasta dan profesional independen (dokter, pengacara, notaris)\n- Nasabah dengan transaksi tunai rutin di atas Rp 100 juta per bulan\n- Badan usaha yang bergerak di bidang properti, perdagangan komoditas\n- Nasabah WNA yang berdomisili di Indonesia")
    pdf.add_subsection("3.3 Risiko Tinggi")
    pdf.add_body("- PEP (Politically Exposed Person) dan keluarganya\n- Nasabah dari negara berisiko tinggi (sesuai daftar FATF)\n- Perusahaan cangkang (shell company) atau SPV tanpa kegiatan usaha jelas\n- Money changer, dealer emas, dan bisnis tunai intensif\n- Organisasi nirlaba yang beroperasi di zona konflik\n- Beneficial Owner yang tidak dapat diidentifikasi secara jelas")
    pdf.add_section("4. Prosedur Customer Due Diligence (CDD)")
    pdf.add_subsection("4.1 Identifikasi Nasabah")
    pdf.add_body("a) Verifikasi identitas menggunakan dokumen resmi yang diterbitkan oleh lembaga berwenang.\nb) Untuk WNI: validasi NIK melalui sistem Dukcapil (real-time).\nc) Untuk badan usaha: verifikasi melalui AHU Online Kemenkumham.\nd) Identifikasi beneficial owner dengan threshold kepemilikan 25% atau lebih.\ne) Pencocokan nama terhadap:\n   - Daftar DTPK (Daftar Terduga Pendanaan Terorisme)\n   - Daftar PEP Indonesia dan Global\n   - Sanctions List (OFAC, UN, EU)\n   - DHBN (Daftar Hitam Bank Nasional)")
    pdf.add_subsection("4.2 Profiling Nasabah")
    pdf.add_body("Setiap nasabah wajib diprofilkan berdasarkan:\na) Tujuan dan sifat hubungan usaha dengan bank\nb) Sumber dana dan sumber kekayaan\nc) Rata-rata penghasilan per bulan\nd) Pola transaksi yang diharapkan (frekuensi, volume, jenis)\ne) Negara asal dana dan negara tujuan transfer\n\nProfil nasabah harus di-review dan di-update:\n- Risiko Rendah: setiap 3 tahun\n- Risiko Menengah: setiap 1 tahun\n- Risiko Tinggi: setiap 6 bulan")
    pdf.add_subsection("4.3 Enhanced Due Diligence (EDD)")
    pdf.add_body("EDD wajib dilakukan untuk nasabah kategori risiko tinggi dengan langkah tambahan:\na) Persetujuan Senior Management (minimal Kepala Cabang) sebelum pembukaan rekening.\nb) Verifikasi sumber dana melalui dokumen pendukung (slip gaji, SPT, laporan keuangan).\nc) On-site visit untuk badan usaha (jika diperlukan).\nd) Pemantauan transaksi lebih intensif (review bulanan).\ne) Dokumentasi lengkap setiap langkah EDD beserta alasan keputusan.")
    pdf.add_section("5. Pemantauan Transaksi (Ongoing Monitoring)")
    pdf.add_body("Bank Nusantara menggunakan sistem pemantauan transaksi berbasis AI dan rule-based:\n\na) Parameter Monitoring Otomatis:\n   - Transaksi tunai >= Rp 500.000.000 (Laporan Transaksi Keuangan Tunai/LTKT)\n   - Transfer dana ke/dari negara berisiko tinggi\n   - Transaksi yang tidak sesuai profil nasabah (anomaly detection)\n   - Structuring/smurfing (pemecahan transaksi untuk menghindari pelaporan)\n   - Rapid movement of funds (dana masuk langsung ditransfer keluar)\n\nb) Red Flags yang Memerlukan Investigasi:\n   - Nasabah menolak memberikan informasi atau memberikan info palsu\n   - Perubahan pola transaksi yang signifikan tanpa penjelasan\n   - Transaksi menggunakan rekening pihak ketiga tanpa hubungan jelas\n   - Penggunaan banyak rekening tanpa tujuan bisnis yang jelas\n   - Transaksi dengan pihak di wilayah sanksi internasional")
    pdf.add_section("6. Pelaporan Transaksi Mencurigakan")
    pdf.add_body("a) Unit Kerja Khusus (UKK) APU-PPT bertanggung jawab atas pelaporan ke PPATK.\nb) Jenis Laporan:\n   - LTKM (Laporan Transaksi Keuangan Mencurigakan): 3 hari kerja sejak terdeteksi\n   - LTKT (Laporan Transaksi Keuangan Tunai): 14 hari kerja\n   - LTS (Laporan Transfer Dana dari dan ke Luar Negeri): 14 hari kerja\nc) Tipping off (memberitahu nasabah bahwa transaksinya dilaporkan) adalah PELANGGARAN HUKUM.\nd) Seluruh laporan bersifat rahasia dan hanya diakses oleh pejabat berwenang.")
    pdf.add_section("7. Sanksi Pelanggaran KYC")
    pdf.add_body("Pelanggaran terhadap kebijakan KYC dapat mengakibatkan:\n\nSanksi Internal:\n- Teguran tertulis dan pencatatan di file personalia\n- Pemotongan bonus/insentif\n- Mutasi ke unit kerja lain\n- Pemberhentian dengan tidak hormat (untuk kasus berat)\n\nSanksi Eksternal (oleh OJK/PPATK):\n- Denda administratif hingga Rp 1 miliar per pelanggaran\n- Larangan menjabat di industri jasa keuangan\n- Pencabutan izin usaha bank (untuk pelanggaran sistemik)\n- Tuntutan pidana sesuai UU TPPU (pidana penjara 3-20 tahun)")
    pdf.output(os.path.join(OUTPUT_DIR, "02_Panduan_KYC.pdf"))
    print("Created: 02_Panduan_KYC.pdf")


def create_kebijakan_kredit_umkm():
    pdf = BankPDF()
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.add_title("Kebijakan Kredit Usaha Mikro, Kecil dan Menengah (UMKM)")
    pdf.add_body("Nomor Dokumen: SOP/KREDIT/003/2025\nTanggal Efektif: 1 Maret 2025\nRevisi ke-3 | Disetujui oleh: Direktur Risk Management")
    pdf.add_section("1. Latar Belakang")
    pdf.add_body("PT Bank Nusantara Tbk berkomitmen untuk mendukung pertumbuhan sektor Usaha Mikro, Kecil dan Menengah (UMKM) sebagai tulang punggung perekonomian Indonesia. Penyaluran kredit UMKM merupakan bagian dari strategi inklusi keuangan bank dan pemenuhan kewajiban regulasi OJK yang mensyaratkan minimal 20% dari total kredit bank disalurkan ke sektor UMKM. Kebijakan ini juga sejalan dengan Program Kredit Usaha Rakyat (KUR) yang didukung oleh Pemerintah melalui subsidi bunga.")
    pdf.add_section("2. Klasifikasi UMKM")
    pdf.add_body("Sesuai UU No. 20 Tahun 2008 dan PP No. 7 Tahun 2021:\n\nUsaha Mikro:\n- Modal usaha: sampai dengan Rp 1 miliar (tidak termasuk tanah dan bangunan)\n- Hasil penjualan tahunan: sampai dengan Rp 2 miliar\n- Contoh: warung makan, pedagang pasar, bengkel kecil\n\nUsaha Kecil:\n- Modal usaha: Rp 1 miliar - Rp 5 miliar\n- Hasil penjualan tahunan: Rp 2 miliar - Rp 15 miliar\n- Contoh: toko retail menengah, kontraktor kecil, UMKM digital\n\nUsaha Menengah:\n- Modal usaha: Rp 5 miliar - Rp 10 miliar\n- Hasil penjualan tahunan: Rp 15 miliar - Rp 50 miliar\n- Contoh: pabrik kecil, perusahaan jasa menengah, franchise")
    pdf.add_section("3. Produk Kredit UMKM")
    pdf.add_subsection("3.1 Kredit Usaha Rakyat (KUR)")
    pdf.add_body("- Plafon: Rp 10 juta - Rp 500 juta (KUR Kecil), maks Rp 10 juta (KUR Mikro)\n- Suku Bunga: 6% per tahun (bersubsidi)\n- Tenor: 3-5 tahun (modal kerja), 5-7 tahun (investasi)\n- Agunan: tanpa agunan untuk KUR Mikro, agunan parsial untuk KUR Kecil\n- Syarat: belum pernah menerima kredit perbankan (kecuali KUR sebelumnya)")
    pdf.add_subsection("3.2 Kredit Modal Kerja (KMK) UMKM")
    pdf.add_body("- Plafon: Rp 50 juta - Rp 5 miliar\n- Suku Bunga: 9-12% per tahun (tergantung profil risiko)\n- Tenor: 1-3 tahun (revolving atau non-revolving)\n- Agunan: fixed asset minimal 100% dari plafon (sertifikat tanah, BPKB)\n- Grace period: 3 bulan untuk usaha baru")
    pdf.add_subsection("3.3 Kredit Investasi UMKM")
    pdf.add_body("- Plafon: Rp 100 juta - Rp 10 miliar\n- Suku Bunga: 10-13% per tahun\n- Tenor: 3-10 tahun\n- Tujuan: pembelian mesin, renovasi tempat usaha, ekspansi kapasitas\n- Agunan: objek yang dibiayai + agunan tambahan")
    pdf.add_subsection("3.4 Kredit Digital UMKM (melalui aplikasi NusantaraBisnis)")
    pdf.add_body("- Plafon: Rp 5 juta - Rp 200 juta\n- Suku Bunga: 8-10% per tahun\n- Approval: otomatis menggunakan credit scoring model (AI-based)\n- Pencairan: instan ke rekening nasabah (H+0)\n- Basis scoring: data transaksi digital (mutasi rekening, payment gateway, e-commerce)")
    pdf.add_section("4. Proses Pengajuan dan Analisis Kredit")
    pdf.add_subsection("4.1 Tahap Pengajuan")
    pdf.add_body("a) Nasabah mengisi formulir aplikasi kredit (offline/online via NusantaraBisnis).\nb) Dokumen yang diperlukan:\n   - KTP dan KK pemohon\n   - NPWP (wajib untuk plafon > Rp 50 juta)\n   - NIB atau Surat Keterangan Usaha dari Kelurahan\n   - Laporan keuangan sederhana (atau mutasi rekening 6 bulan terakhir)\n   - Foto tempat usaha dan dokumentasi usaha\n   - Dokumen agunan (sertifikat tanah, BPKB) jika diperlukan\nc) Relationship Manager (RM) melakukan kunjungan awal ke lokasi usaha (on-site visit).")
    pdf.add_subsection("4.2 Analisis Kredit (5C Analysis)")
    pdf.add_body("a) Character: riwayat kredit di BI Checking/SLIK, track record bisnis, referensi\nb) Capacity: kemampuan bayar berdasarkan cash flow, rasio angsuran terhadap pendapatan (DSR maks 40%)\nc) Capital: modal sendiri yang ditanamkan dalam usaha (minimal 30% dari total kebutuhan)\nd) Collateral: nilai jaminan minimal 100% dari plafon kredit (berdasarkan appraisal independent)\ne) Condition: kondisi ekonomi makro, prospek industri/sektor usaha")
    pdf.add_subsection("4.3 Credit Scoring Model")
    pdf.add_body("Bank Nusantara menggunakan credit scoring model berbasis AI untuk mempercepat proses analisis:\n\nVariabel Scoring:\n- Riwayat pembayaran kredit sebelumnya (weight: 30%)\n- Rasio hutang terhadap pendapatan (weight: 20%)\n- Lama usaha berjalan (weight: 15%)\n- Volume transaksi digital per bulan (weight: 15%)\n- Sektor usaha dan lokasi (weight: 10%)\n- Stabilitas saldo rekening (weight: 10%)\n\nKategori Skor:\n- 750-1000: Very Good (auto-approve untuk plafon <= Rp 100 juta)\n- 600-749: Good (review singkat oleh RM)\n- 400-599: Fair (review mendalam + agunan tambahan)\n- 200-399: Poor (tolak atau KUR dengan pendampingan)\n- 0-199: Very Poor (tolak)")
    pdf.add_section("5. Kewenangan Persetujuan Kredit")
    pdf.add_body("Tingkat kewenangan berdasarkan plafon:\n\nPlafon                  | Pejabat Pemutus\n<= Rp 100 juta          | Kepala Unit/KCP\nRp 100 juta - 500 juta  | Kepala Cabang\nRp 500 juta - 2 miliar  | Area Manager + Komite Kredit Wilayah\nRp 2 miliar - 5 miliar  | Regional Manager + Komite Kredit Regional\n> Rp 5 miliar           | Direksi + Komite Kredit Head Office\n\nKetentuan:\n- Four-eyes principle: minimal 2 pejabat untuk setiap keputusan kredit\n- Segregation of duties: RM pengaju tidak boleh merangkap sebagai pemutus kredit")
    pdf.add_section("6. Monitoring dan Kolektibilitas")
    pdf.add_body("Status kolektibilitas mengacu pada POJK No. 40/POJK.03/2019:\n\n1 - Lancar: pembayaran tepat waktu, tidak ada tunggakan\n2 - Dalam Perhatian Khusus (DPK): tunggakan 1-90 hari\n3 - Kurang Lancar: tunggakan 91-120 hari\n4 - Diragukan: tunggakan 121-180 hari\n5 - Macet: tunggakan > 180 hari\n\nEarly Warning System (EWS):\n- Monitoring otomatis penurunan saldo rekening operasional\n- Alert jika DSR nasabah meningkat > 50%\n- Notifikasi jika ada transaksi tidak biasa (pattern anomaly)\n- Dashboard monitoring NPL per cabang, region, dan sektor usaha")
    pdf.add_section("7. Restrukturisasi Kredit")
    pdf.add_body("Nasabah yang mengalami kesulitan pembayaran dapat mengajukan restrukturisasi:\n\nJenis Restrukturisasi:\na) Penurunan suku bunga\nb) Perpanjangan tenor (maksimal 2x tenor awal)\nc) Pengurangan tunggakan bunga\nd) Penambahan fasilitas kredit (untuk nasabah yang usahanya masih viable)\ne) Konversi kredit menjadi penyertaan modal sementara\n\nSyarat Restrukturisasi:\n- Nasabah memiliki itikad baik (kooperatif)\n- Usaha masih berjalan dan memiliki prospek\n- Nasabah menyerahkan rencana bisnis (business plan) yang realistis\n- Persetujuan oleh Komite Restrukturisasi Kredit")
    pdf.output(os.path.join(OUTPUT_DIR, "03_Kebijakan_Kredit_UMKM.pdf"))
    print("Created: 03_Kebijakan_Kredit_UMKM.pdf")


def create_panduan_aml():
    pdf = BankPDF()
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.add_title("Panduan Anti Money Laundering (AML)")
    pdf.add_body("Nomor Dokumen: SOP/COMPL/004/2025\nTanggal Efektif: 1 Januari 2025\nRevisi ke-6 | Disetujui oleh: Direktur Kepatuhan & Tata Kelola")
    pdf.add_section("1. Definisi dan Konsep Dasar")
    pdf.add_body("Pencucian Uang (Money Laundering) adalah perbuatan menempatkan, mentransfer, mengalihkan, membelanjakan, membayarkan, menghibahkan, menitipkan, membawa ke luar negeri, mengubah bentuk, menukarkan dengan mata uang atau surat berharga, atau perbuatan lain atas Harta Kekayaan yang diketahuinya atau patut diduganya merupakan hasil tindak pidana, dengan tujuan menyembunyikan atau menyamarkan asal usul Harta Kekayaan.")
    pdf.add_subsection("1.1 Tahapan Pencucian Uang")
    pdf.add_body("a) Placement (Penempatan): memasukkan uang hasil kejahatan ke dalam sistem keuangan.\n   Contoh: menyetor tunai dalam jumlah kecil ke banyak rekening (structuring).\n\nb) Layering (Pelapisan): memisahkan uang dari sumber kejahatan melalui transaksi yang kompleks.\n   Contoh: transfer antar bank, pembelian instrumen keuangan, transaksi lintas negara.\n\nc) Integration (Integrasi): mengembalikan uang yang telah 'bersih' ke dalam ekonomi legal.\n   Contoh: investasi di properti, pendirian perusahaan, pembelian aset mewah.")
    pdf.add_section("2. Kewajiban Bank dalam Pencegahan AML")
    pdf.add_body("PT Bank Nusantara Tbk memiliki kewajiban untuk:\n\na) Menerapkan prinsip Customer Due Diligence (CDD) dan Enhanced Due Diligence (EDD)\nb) Memantau transaksi nasabah secara berkesinambungan (ongoing monitoring)\nc) Melaporkan Transaksi Keuangan Mencurigakan (TKM) ke PPATK\nd) Melaporkan Transaksi Keuangan Tunai >= Rp 500 juta ke PPATK\ne) Melaporkan Transfer Dana dari dan ke Luar Negeri ke PPATK\nf) Menyimpan dokumen dan catatan transaksi minimal 5 tahun\ng) Melaksanakan program pelatihan APU-PPT secara berkala\nh) Memiliki Unit Kerja Khusus (UKK) yang bertanggung jawab atas pelaksanaan APU-PPT")
    pdf.add_section("3. Red Flags - Indikator Transaksi Mencurigakan")
    pdf.add_subsection("3.1 Red Flags Terkait Nasabah")
    pdf.add_bullet("Nasabah menolak memberikan informasi atau memberikan informasi yang tidak konsisten")
    pdf.add_bullet("Nasabah menggunakan identitas palsu atau identitas orang lain")
    pdf.add_bullet("Nasabah memiliki banyak rekening tanpa alasan bisnis yang jelas")
    pdf.add_bullet("Nasabah yang baru membuka rekening langsung melakukan transaksi besar")
    pdf.add_bullet("Nasabah yang sangat khawatir tentang pelaporan atau batas transaksi")
    pdf.add_subsection("3.2 Red Flags Terkait Transaksi")
    pdf.add_bullet("Transaksi tunai yang tidak lazim (frekuensi tinggi, jumlah di bawah batas pelaporan)")
    pdf.add_bullet("Transfer ke/dari negara berisiko tinggi tanpa alasan bisnis")
    pdf.add_bullet("Transaksi yang tidak sesuai dengan profil bisnis nasabah")
    pdf.add_bullet("Penggunaan rekening untuk transaksi transit (uang masuk langsung keluar)")
    pdf.add_bullet("Transaksi round-trip: dana dikirim ke luar negeri dan kembali dari entitas berbeda")
    pdf.add_bullet("Pembelian instrumen keuangan (cek, giro bilyet) dalam jumlah besar dengan tunai")
    pdf.add_subsection("3.3 Red Flags Terkait Kredit")
    pdf.add_bullet("Pelunasan kredit secara tiba-tiba dari sumber yang tidak jelas")
    pdf.add_bullet("Permohonan kredit dengan agunan yang nilainya sangat tinggi dari sumber tidak jelas")
    pdf.add_bullet("Nasabah yang meminta pencairan kredit ditransfer ke pihak ketiga")
    pdf.add_section("4. Sistem Pemantauan Transaksi")
    pdf.add_body("Bank Nusantara menggunakan sistem pemantauan transaksi berlapis:\n\nLayer 1 - Rule-Based Monitoring:\n- Threshold monitoring: transaksi tunai >= Rp 500 juta\n- Velocity monitoring: frekuensi transaksi melebihi 50x per hari\n- Pattern monitoring: structuring, smurfing, round-tripping\n- Blacklist monitoring: transaksi dengan pihak dalam daftar sanksi\n\nLayer 2 - AI-Based Monitoring:\n- Anomaly detection menggunakan machine learning\n- Network analysis untuk mendeteksi pola hubungan mencurigakan\n- Behavioral analysis untuk mendeteksi perubahan pola transaksi\n- Natural Language Processing untuk analisis informasi dari sumber terbuka\n\nLayer 3 - Manual Review:\n- Investigation oleh tim Compliance untuk alert yang di-generate sistem\n- Prioritisasi berdasarkan risk score dan materialitas\n- Dokumentasi lengkap setiap investigasi dan keputusan")
    pdf.add_section("5. Pelaporan ke PPATK")
    pdf.add_body("Jenis Laporan dan Tenggat Waktu:\n\na) LTKM (Laporan Transaksi Keuangan Mencurigakan):\n   - Disampaikan paling lambat 3 hari kerja sejak transaksi diketahui mencurigakan\n   - Format: melalui aplikasi goAML (PPATK online reporting)\n   - Informasi: identitas nasabah, deskripsi transaksi, alasan kecurigaan\n\nb) LTKT (Laporan Transaksi Keuangan Tunai):\n   - Transaksi tunai >= Rp 500.000.000\n   - Disampaikan paling lambat 14 hari kerja setelah transaksi\n\nc) LTDLN (Laporan Transfer Dana Luar Negeri):\n   - Transfer masuk/keluar >= Rp 100.000.000\n   - Disampaikan paling lambat 14 hari kerja setelah transaksi\n\nPENTING: Tipping Off adalah DILARANG. Petugas bank DILARANG memberitahukan kepada nasabah bahwa transaksinya telah dilaporkan ke PPATK. Pelanggaran tipping off diancam pidana penjara 3-5 tahun.")
    pdf.add_section("6. Program Pelatihan APU-PPT")
    pdf.add_body("Seluruh karyawan Bank Nusantara wajib mengikuti pelatihan APU-PPT:\n\na) Pelatihan Dasar (untuk seluruh karyawan baru):\n   - Pengenalan UU TPPU dan UU TPPT\n   - Konsep dasar KYC dan CDD\n   - Cara mengenali transaksi mencurigakan\n   - Prosedur pelaporan internal\n\nb) Pelatihan Lanjutan (untuk frontliner dan compliance):\n   - Case study pencucian uang aktual\n   - Teknik investigasi transaksi mencurigakan\n   - Update regulasi terbaru\n   - Penggunaan sistem pemantauan transaksi\n\nc) Pelatihan Khusus (untuk manajemen senior):\n   - Tanggung jawab hukum direksi dan dewan komisaris\n   - Governance framework APU-PPT\n   - Komunikasi dengan regulator\n\nFrekuensi: minimal 1x per tahun, dengan refreshment setiap 6 bulan.")
    pdf.output(os.path.join(OUTPUT_DIR, "04_Panduan_AML.pdf"))
    print("Created: 04_Panduan_AML.pdf")


def create_prosedur_restrukturisasi():
    pdf = BankPDF()
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.add_title("Prosedur Restrukturisasi Kredit")
    pdf.add_body("Nomor Dokumen: SOP/KREDIT/005/2025\nTanggal Efektif: 1 Februari 2025\nRevisi ke-4 | Disetujui oleh: Direktur Risk Management")
    pdf.add_section("1. Definisi dan Tujuan")
    pdf.add_body("Restrukturisasi kredit adalah upaya perbaikan yang dilakukan bank terhadap debitur yang mengalami kesulitan untuk memenuhi kewajibannya. Tujuan restrukturisasi adalah untuk menyelamatkan kredit bermasalah dengan tetap mempertahankan hubungan bisnis yang saling menguntungkan, sesuai dengan prinsip kehati-hatian dan regulasi OJK.")
    pdf.add_section("2. Dasar Hukum")
    pdf.add_body("- POJK No. 40/POJK.03/2019 tentang Penilaian Kualitas Aset Bank Umum\n- POJK No. 48/POJK.03/2020 tentang Stimulus Perekonomian Nasional (perpanjangan)\n- SE OJK No. 14/SEOJK.03/2020 tentang Kebijakan Countercyclical Dampak COVID-19\n- Kebijakan Internal: Surat Keputusan Direksi No. SK/DIR/2025/001")
    pdf.add_section("3. Kriteria Debitur yang Dapat Direstrukturisasi")
    pdf.add_body("Debitur dapat diajukan untuk restrukturisasi jika memenuhi kriteria:\n\na) Debitur mengalami penurunan kemampuan bayar yang bersifat sementara\nb) Usaha debitur masih berjalan dan memiliki prospek yang baik\nc) Debitur menunjukkan itikad baik (kooperatif, terbuka dalam memberikan informasi)\nd) Debitur menyerahkan proposal restrukturisasi yang realistis\ne) Hasil analisis menunjukkan bahwa restrukturisasi lebih menguntungkan dibandingkan penagihan/penghapusan\n\nKriteria Penolakan:\n- Debitur terbukti melakukan fraud atau penyalahgunaan kredit\n- Usaha sudah tidak berjalan (tutup permanen)\n- Debitur tidak kooperatif atau menolak memberikan informasi\n- Kredit sudah pernah direstrukturisasi 2x dan gagal")
    pdf.add_section("4. Jenis Restrukturisasi")
    pdf.add_subsection("4.1 Penurunan Suku Bunga")
    pdf.add_body("- Menurunkan suku bunga dari rate existing ke rate yang lebih rendah\n- Maksimal penurunan: 3% dari suku bunga existing\n- Berlaku untuk periode 6-12 bulan, setelah itu di-review\n- Contoh: dari 12% menjadi 9% selama 12 bulan")
    pdf.add_subsection("4.2 Perpanjangan Jangka Waktu")
    pdf.add_body("- Memperpanjang tenor kredit untuk menurunkan angsuran bulanan\n- Maksimal perpanjangan: 2x tenor awal (contoh: dari 3 tahun menjadi 9 tahun)\n- Diiringi dengan recalculation angsuran\n- Cocok untuk debitur yang mengalami penurunan cash flow sementara")
    pdf.add_subsection("4.3 Pengurangan Tunggakan Bunga")
    pdf.add_body("- Bank dapat menghapuskan sebagian tunggakan bunga (bukan pokok)\n- Maksimal penghapusan: 50% dari total tunggakan bunga\n- Harus disetujui oleh Komite Restrukturisasi Head Office\n- Debitur wajib membayar minimal 50% tunggakan bunga secara upfront")
    pdf.add_subsection("4.4 Penambahan Fasilitas Kredit")
    pdf.add_body("- Diberikan kepada debitur yang memerlukan tambahan modal kerja untuk pemulihan usaha\n- Plafon tambahan maksimal 30% dari outstanding kredit\n- Dikenakan suku bunga pasar dan tenor sesuai kebutuhan usaha\n- Wajib disertai dengan agunan tambahan atau personal guarantee")
    pdf.add_subsection("4.5 Konversi Kredit Menjadi Penyertaan Modal Sementara")
    pdf.add_body("- Sebagian atau seluruh kredit dikonversi menjadi penyertaan modal bank di perusahaan debitur\n- Hanya untuk kredit korporasi dengan outstanding > Rp 50 miliar\n- Bank memiliki hak suara dalam RUPS sesuai proporsi penyertaan\n- Exit strategy: penjualan penyertaan dalam waktu 5 tahun")
    pdf.add_section("5. Prosedur Pengajuan Restrukturisasi")
    pdf.add_body("Tahap 1 - Inisiasi (Minggu 1-2):\na) RM mengidentifikasi debitur yang memerlukan restrukturisasi berdasarkan EWS\nb) RM melakukan kunjungan ke debitur untuk assessment awal\nc) Debitur menyerahkan proposal restrukturisasi dan dokumen pendukung:\n   - Laporan keuangan terkini\n   - Business plan untuk 1-3 tahun ke depan\n   - Bukti penurunan pendapatan/omzet\n   - Rencana pembayaran yang diusulkan\n\nTahap 2 - Analisis (Minggu 2-4):\na) Credit Analyst melakukan analisis kelayakan restrukturisasi\nb) Penilaian ulang agunan oleh appraiser independent\nc) Stress test: simulasi kemampuan bayar dalam berbagai skenario\nd) Legal review oleh Legal Division (untuk kredit > Rp 1 miliar)\n\nTahap 3 - Persetujuan (Minggu 4-5):\na) Presentasi proposal ke Komite Restrukturisasi\nb) Keputusan: DISETUJUI / DISETUJUI DENGAN SYARAT / DITOLAK\nc) Jika disetujui, pembuatan addendum perjanjian kredit\n\nTahap 4 - Implementasi (Minggu 5-6):\na) Penandatanganan addendum perjanjian kredit\nb) Input perubahan ke Core Banking System\nc) Monitoring intensif selama 6 bulan pertama\nd) Reporting ke OJK sesuai ketentuan")
    pdf.add_section("6. Kewenangan Persetujuan Restrukturisasi")
    pdf.add_body("Outstanding          | Pejabat Pemutus\n<= Rp 500 juta       | Komite Kredit Cabang (KCC)\nRp 500 jt - 5 miliar | Komite Kredit Wilayah (KKW)\nRp 5 miliar - 25 M   | Komite Kredit Head Office (KKHO)\n> Rp 25 miliar       | Direksi + Dewan Komisaris")
    pdf.add_section("7. Monitoring Pasca Restrukturisasi")
    pdf.add_body("a) RM melakukan kunjungan berkala:\n   - Bulan 1-6: kunjungan setiap bulan\n   - Bulan 7-12: kunjungan setiap 2 bulan\n   - Setelah 12 bulan: kunjungan setiap quarter\n\nb) Parameter Monitoring:\n   - Ketepatan waktu pembayaran angsuran\n   - Perkembangan usaha (omzet, jumlah karyawan, outlet)\n   - Kondisi agunan (kunjungan dan foto berkala)\n   - Kepatuhan terhadap covenant restrukturisasi\n\nc) Reporting:\n   - Laporan bulanan ke Unit Recovery & Restructuring\n   - Laporan triwulanan ke Komite Restrukturisasi\n   - Laporan semesteran ke OJK (melalui LBUS)")
    pdf.output(os.path.join(OUTPUT_DIR, "05_Prosedur_Restrukturisasi.pdf"))
    print("Created: 05_Prosedur_Restrukturisasi.pdf")


def create_panduan_perbankan_digital():
    pdf = BankPDF()
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.add_title("Panduan Layanan Perbankan Digital")
    pdf.add_body("Nomor Dokumen: SOP/DIGITAL/006/2025\nTanggal Efektif: 1 Januari 2025\nRevisi ke-3 | Disetujui oleh: Direktur Teknologi & Digital Banking")
    pdf.add_section("1. Tentang Layanan Digital Bank Nusantara")
    pdf.add_body("Bank Nusantara menyediakan layanan perbankan digital yang komprehensif melalui beberapa channel:\n\na) NusantaraMobile: Aplikasi mobile banking untuk nasabah retail dan priority\nb) NusantaraBisnis: Aplikasi mobile untuk nasabah UMKM dan korporasi\nc) NusantaraNet: Internet banking via web browser\nd) QRIS Bank Nusantara: Layanan pembayaran menggunakan QR code\ne) NusantaraAPI: Open Banking API untuk integrasi dengan mitra bisnis\n\nSeluruh layanan digital telah memenuhi standar keamanan:\n- PCI DSS Level 1 Certified\n- ISO 27001 Information Security Management\n- SSL/TLS 1.3 Encryption\n- Two-Factor Authentication (2FA)")
    pdf.add_section("2. NusantaraMobile - Fitur dan Layanan")
    pdf.add_body("Fitur Utama:\na) Transfer Dana:\n   - Antar rekening Bank Nusantara: gratis, real-time\n   - Ke bank lain via BI-FAST: Rp 2.500 per transaksi, real-time\n   - Ke e-wallet (GoPay, OVO, Dana, ShopeePay): real-time\n   - Transfer terjadwal dan recurring\n   - Limit: Rp 500 juta/hari (bisa dinaikkan via cabang)\n\nb) Pembayaran:\n   - Tagihan: PLN, PDAM, internet, TV kabel, asuransi\n   - Pajak: PBB, PPh, PPN via e-Billing\n   - Pendidikan: SPP universitas, sekolah\n   - Top up: pulsa, paket data, e-toll, e-money\n   - QRIS: scan QR untuk pembayaran di merchant\n\nc) Investasi (NusantaraInvest):\n   - Deposito online: pembukaan, perpanjangan, pencairan\n   - Reksa dana: pembelian, penjualan, switching\n   - SBN (Surat Berharga Negara): pembelian saat masa penawaran\n   - Emas digital: beli, jual, tabung, tarik fisik\n\nd) Layanan Lainnya:\n   - Pembukaan rekening baru (e-Account Opening)\n   - Pengajuan kartu kredit\n   - Mutasi rekening dan cetak e-statement\n   - Blokir/buka blokir kartu debit\n   - Pengaduan nasabah (e-complaint)")
    pdf.add_section("3. Keamanan Transaksi Digital")
    pdf.add_body("Multi-Layer Security:\n\nLayer 1 - Device Binding:\n- Satu akun hanya bisa diakses dari 1 perangkat\n- Jika ganti perangkat, wajib re-registrasi via ATM atau cabang\n- Deteksi jailbreak/root: akses otomatis diblokir\n\nLayer 2 - Authentication:\n- Login: PIN 6 digit + biometrik (fingerprint/face ID)\n- Transaksi: OTP via SMS atau soft token\n- Transaksi besar (> Rp 100 juta): additional verification via video call\n\nLayer 3 - Transaction Monitoring:\n- Real-time fraud detection menggunakan AI/ML\n- Behavioral biometrics: analisis pola ketikan dan gestur\n- Geo-location monitoring: deteksi transaksi dari lokasi tidak biasa\n- Velocity check: limit jumlah transaksi per jam/hari\n\nLayer 4 - Incident Response:\n- Nasabah bisa blokir akun mandiri via fitur Emergency Lock\n- Call center 24/7: 14000 atau +62-21-5299-7777\n- Pengembalian dana untuk transaksi fraud yang terbukti (maks 14 hari kerja)")
    pdf.add_section("4. NusantaraBisnis - Layanan UMKM Digital")
    pdf.add_body("Fitur khusus untuk pelaku UMKM:\n\na) Cash Management:\n   - Bulk payment (pembayaran gaji, vendor, supplier)\n   - Cash pooling antar rekening\n   - Virtual account untuk penerimaan pembayaran\n   - Real-time balance monitoring\n\nb) Trade Finance Digital:\n   - Pembukaan LC (Letter of Credit) online\n   - Bank Guarantee online\n   - SKBDN (Surat Kredit Berdokumen Dalam Negeri)\n\nc) Kredit Digital UMKM:\n   - Pengajuan kredit online (KMK, KI, KUR)\n   - Tracking status pengajuan\n   - Pencairan instan untuk KUR Mikro\n   - Dashboard monitoring pembayaran angsuran\n\nd) Laporan dan Analitik:\n   - Dashboard cash flow harian/mingguan/bulanan\n   - Analisis tren penerimaan dan pengeluaran\n   - Export laporan ke PDF/Excel\n   - Integrasi dengan software akuntansi (Jurnal, Accurate)")
    pdf.add_section("5. Open Banking API (NusantaraAPI)")
    pdf.add_body("Bank Nusantara menyediakan Open Banking API untuk integrasi dengan ekosistem digital:\n\nAPI yang Tersedia:\na) Account Information API: saldo, mutasi, informasi rekening\nb) Payment Initiation API: transfer, pembayaran tagihan\nc) Merchant API: integrasi pembayaran untuk e-commerce\nd) Lending API: pengajuan kredit digital oleh mitra fintech\ne) Identity Verification API: verifikasi identitas nasabah untuk mitra\n\nStandar API:\n- RESTful API dengan format JSON\n- OAuth 2.0 untuk authentication\n- Rate limiting: 100 request/menit per client\n- Sandbox environment untuk development\n- SLA: 99.9% uptime, response time < 200ms\n\nPartner Ecosystem:\n- E-commerce: Tokopedia, Shopee, Bukalapak\n- Fintech lending: Investree, Modalku\n- Insurtech: PasarPolis, Qoala\n- Accounting: Jurnal by Mekari, Accurate\n- POS system: Moka, iSeller, Pawoon")
    pdf.add_section("6. Penanganan Keluhan dan Insiden")
    pdf.add_body("a) Channel Pengaduan:\n   - Dalam aplikasi: menu Bantuan > Pengaduan\n   - Call center: 14000 (24/7)\n   - Email: pengaduan@banknusantara.co.id\n   - Sosial media: @banknusantara (Twitter/X, Instagram)\n   - Walk-in ke cabang terdekat\n\nb) SLA Penanganan:\n   - Pengaduan biasa: 20 hari kerja\n   - Pengaduan fraud/unauthorized transaction: 14 hari kerja\n   - Gangguan sistem: 4 jam (P1), 8 jam (P2), 24 jam (P3)\n\nc) Eskalasi:\n   - Level 1: Customer Service Agent\n   - Level 2: Team Lead Customer Experience\n   - Level 3: Head of Digital Banking\n   - Level 4: Direktur Teknologi & Digital Banking\n\nd) Nasabah yang tidak puas dengan penyelesaian dapat mengajukan mediasi ke OJK sesuai POJK No. 1/POJK.07/2014.")
    pdf.output(os.path.join(OUTPUT_DIR, "06_Panduan_Perbankan_Digital.pdf"))
    print("Created: 06_Panduan_Perbankan_Digital.pdf")


if __name__ == "__main__":
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    create_sop_pembukaan_rekening()
    create_panduan_kyc()
    create_kebijakan_kredit_umkm()
    create_panduan_aml()
    create_prosedur_restrukturisasi()
    create_panduan_perbankan_digital()
    print("\nAll PDFs created successfully!")
